In [1]:
import arules as ar
from arules.utils import five_quantile_based_bins, top_bottom_10, top_5_variant_variables
import pandas as pd

In [2]:
df = pd.read_csv('partos-cesarianas-v1.csv')
print (df)

                         Região   Ano  Nº Total de Partos  Nº Cesarianas  \
0           Região de Saúde LVT  2013            178835.0        52136.0
1           Região de Saúde LVT  2014            177713.0        47747.0
2           Região de Saúde LVT  2015            183294.0        48313.0
3           Região de Saúde LVT  2016            189136.0        49712.0
4           Região de Saúde LVT  2017            189270.0        49898.0
5           Região de Saúde LVT  2018            191661.0        52578.0
6           Região de Saúde LVT  2019            193305.0        54539.0
7           Região de Saúde LVT  2020            182650.0        53504.0
8           Região de Saúde LVT  2021            162548.0        47935.0
9           Região de Saúde LVT  2022            159821.0        50196.0
10          Região de Saúde LVT  2023            162445.0        51081.0
11        Região de Saúde Norte  2013            144616.0        46387.0
12        Região de Saúde Norte  2014            139349.0        40110.0
13        Região de Saúde Norte  2015            144524.0        42695.0
14        Região de Saúde Norte  2016            150801.0        43909.0
15        Região de Saúde Norte  2017            148049.0        41629.0
16        Região de Saúde Norte  2018            147521.0        42554.0
17        Região de Saúde Norte  2019            149255.0        44741.0
18        Região de Saúde Norte  2020            147344.0        45079.0
19        Região de Saúde Norte  2021            132783.0        42010.0
20        Região de Saúde Norte  2022            140682.0        44888.0
21        Região de Saúde Norte  2023            143423.0        47938.0
22  Região de Saúde do Alentejo  2013             17439.0         5589.0
23  Região de Saúde do Alentejo  2014             16460.0         4698.0
24  Região de Saúde do Alentejo  2015             17185.0         4521.0
25  Região de Saúde do Alentejo  2016             17701.0         4842.0
26  Região de Saúde do Alentejo  2017             17158.0         5091.0
27  Região de Saúde do Alentejo  2018             16773.0         5241.0
28  Região de Saúde do Alentejo  2019             16333.0         5373.0
29  Região de Saúde do Alentejo  2020             16398.0         5176.0
30  Região de Saúde do Alentejo  2021             15242.0         5165.0
31  Região de Saúde do Alentejo  2022             15188.0         5800.0
32  Região de Saúde do Alentejo  2023             15336.0         5896.0
33   Região de Saúde do Algarve  2013             22364.0         7060.0
34   Região de Saúde do Algarve  2014             21446.0         5732.0
35   Região de Saúde do Algarve  2015             22781.0         5680.0
36   Região de Saúde do Algarve  2016             23631.0         6110.0
37   Região de Saúde do Algarve  2017             23359.0         6240.0
38   Região de Saúde do Algarve  2018             23823.0         6253.0
39   Região de Saúde do Algarve  2019             24429.0         7467.0
40   Região de Saúde do Algarve  2020             23518.0         6568.0
41   Região de Saúde do Algarve  2021             22236.0         6473.0
42   Região de Saúde do Algarve  2022             21585.0         6606.0
43   Região de Saúde do Algarve  2023             22990.0         7259.0
44    Região de Saúde do Centro  2013             75571.0        22407.0
45    Região de Saúde do Centro  2014             72460.0        20375.0
46    Região de Saúde do Centro  2015             75850.0        20327.0
47    Região de Saúde do Centro  2016             77748.0        21013.0
48    Região de Saúde do Centro  2017             76138.0        21684.0
49    Região de Saúde do Centro  2018             76040.0        21540.0
50    Região de Saúde do Centro  2019             74369.0        20567.0
51    Região de Saúde do Centro  2020             74294.0        20415.0
52    Região de Saúde do Centro  2021             67024.0        19357.0
53    Região de Saúde do Centro  2022             70748.0        21422.0
54    Região de Saúde do Centro  2023             76322.0        22744.0

    Proporção_de_Cesarianas Nível_de_Risco_Cesariana  \
0                      0.29                    Baixo
1                      0.27                    Baixo
2                      0.26                    Baixo
3                      0.26                    Baixo
4                      0.26                    Baixo
5                      0.27                    Baixo
6                      0.28                    Baixo
7                      0.29                    Baixo
8                      0.29                    Baixo
9                      0.31                 Moderado
10                     0.31                 Moderado
11                     0.32                 Moderado
12                     0.29                    Baixo
13                     0.30                    Baixo
14                     0.29                    Baixo
15                     0.28                    Baixo
16                     0.29                    Baixo
17                     0.30                    Baixo
18                     0.31                 Moderado
19                     0.32                 Moderado
20                     0.32                 Moderado
21                     0.33                 Moderado
22                     0.32                 Moderado
23                     0.29                    Baixo
24                     0.26                    Baixo
25                     0.27                    Baixo
26                     0.30                    Baixo
27                     0.31                 Moderado
28                     0.33                 Moderado
29                     0.32                 Moderado
30                     0.34                 Moderado
31                     0.38                 Moderado
32                     0.38                 Moderado
33                     0.32                 Moderado
34                     0.27                    Baixo
35                     0.25                    Baixo
36                     0.26                    Baixo
37                     0.27                    Baixo
38                     0.26                    Baixo
39                     0.31                 Moderado
40                     0.28                    Baixo
41                     0.29                    Baixo
42                     0.31                 Moderado
43                     0.32                 Moderado
44                     0.30                    Baixo
45                     0.28                    Baixo
46                     0.27                    Baixo
47                     0.27                    Baixo
48                     0.28                    Baixo
49                     0.28                    Baixo
50                     0.28                    Baixo
51                     0.27                    Baixo
52                     0.29                    Baixo
53                     0.30                    Baixo
54                     0.30                    Baixo

    Classificação_de_Nível_de_Risco
0                                 1
1                                 1
2                                 1
3                                 1
4                                 1
5                                 1
6                                 1
7                                 1
8                                 1
9                                 2
10                                2
11                                2
12                                1
13                                1
14                                1
15                                1
16                                1
17                                1
18                                2
19                                2
20                                2
21                                2
22                                2
23                                1
24                                1
25                                1
26                                1
27                                2
28                                2
29                                2
30                                2
31                                2
32                                2
33                                2
34                                1
35                                1
36                                1
37                                1
38                                1
39                                2
40                                1
41                                1
42                                2
43                                2
44                                1
45                                1
46                                1
47                                1
48                                1
49                                1
50                                1
51                                1
52                                1
53                                1
54                                1

In [3]:
qunatiles = five_quantile_based_bins(df['Proporção_de_Cesarianas'])
qunatiles

0      (0.28 - 0.3]
1     [0.25 - 0.27]
2     [0.25 - 0.27]
3     [0.25 - 0.27]
4     [0.25 - 0.27]
5     [0.25 - 0.27]
6     (0.27 - 0.28]
7      (0.28 - 0.3]
8      (0.28 - 0.3]
9      (0.3 - 0.32]
10     (0.3 - 0.32]
11     (0.3 - 0.32]
12     (0.28 - 0.3]
13     (0.28 - 0.3]
14     (0.28 - 0.3]
15    (0.27 - 0.28]
16     (0.28 - 0.3]
17     (0.28 - 0.3]
18     (0.3 - 0.32]
19     (0.3 - 0.32]
20     (0.3 - 0.32]
21    (0.32 - 0.38]
22     (0.3 - 0.32]
23     (0.28 - 0.3]
24    [0.25 - 0.27]
25    [0.25 - 0.27]
26     (0.28 - 0.3]
27     (0.3 - 0.32]
28    (0.32 - 0.38]
29     (0.3 - 0.32]
30    (0.32 - 0.38]
31    (0.32 - 0.38]
32    (0.32 - 0.38]
33     (0.3 - 0.32]
34    [0.25 - 0.27]
35    [0.25 - 0.27]
36    [0.25 - 0.27]
37    [0.25 - 0.27]
38    [0.25 - 0.27]
39     (0.3 - 0.32]
40    (0.27 - 0.28]
41     (0.28 - 0.3]
42     (0.3 - 0.32]
43     (0.3 - 0.32]
44     (0.28 - 0.3]
45    (0.27 - 0.28]
46    [0.25 - 0.27]
47    [0.25 - 0.27]
48    (0.27 - 0.28]
49    (0.27 - 0.28]
50    (0.27 - 0.28]
51    [0.25 - 0.27]
52     (0.28 - 0.3]
53     (0.28 - 0.3]
54     (0.28 - 0.3]
Name: Proporção_de_Cesarianas, dtype: category
Categories (5, object): ['[0.25 - 0.27]' < '(0.27 - 0.28]' < '(0.28 - 0.3]' < '(0.3 - 0.32]' < '(0.32 - 0.38]']

In [4]:
rules, supp_dict = ar.create_association_rules(df, max_cols=2, binning_method=five_quantile_based_bins)
rules

Calculating all relevant supports
100%|██████████| 28/28 [00:00<00:00, 1226.61it/s]

Calculating all feature level rules per variable level rule
100%|██████████| 42/42 [00:00<00:00, 1441.72it/s]
Overall # of Rules:  866

,antecedent,consequent,rule print,ant_count,con_count,rule_count,ant_supp,con_supp,rule_supp,confidence,lift,# of all records
0,{'Proporção_de_Cesarianas': '0.25'},{'Ano': '2015'},Proporção_de_Cesarianas=0.25 ==> Ano=2015,1,5,1,0.018182,0.090909,0.018182,1.000,11.0000,55
1,{'Proporção_de_Cesarianas': '0.34'},{'Ano': '2021'},Proporção_de_Cesarianas=0.34 ==> Ano=2021,1,5,1,0.018182,0.090909,0.018182,1.000,11.0000,55
2,{'Ano': '2015'},{'Proporção_de_Cesarianas': '0.25'},Ano=2015 ==> Proporção_de_Cesarianas=0.25,5,1,1,0.090909,0.018182,0.018182,0.200,11.0000,55
3,{'Ano': '2021'},{'Proporção_de_Cesarianas': '0.34'},Ano=2021 ==> Proporção_de_Cesarianas=0.34,5,1,1,0.090909,0.018182,0.018182,0.200,11.0000,55
4,{'Proporção_de_Cesarianas': '0.33'},{'Ano': '2019'},Proporção_de_Cesarianas=0.33 ==> Ano=2019,2,5,1,0.036364,0.090909,0.018182,0.500,5.5000,55
...,...,...,...,...,...,...,...,...,...,...,...,...
861,{'Ano': '2023'},{'Classificação_de_Nível_de_Risco': '1'},Ano=2023 ==> Classificação_de_Nível_de_Risco=1,5,37,1,0.090909,0.672727,0.018182,0.200,0.2973,55
862,{'Nível_de_Risco_Cesariana': 'Baixo'},{'Ano': '2022'},Nível_de_Risco_Cesariana=Baixo ==> Ano=2022,37,5,1,0.672727,0.090909,0.018182,0.027,0.2973,55
863,{'Nível_de_Risco_Cesariana': 'Baixo'},{'Ano': '2023'},Nível_de_Risco_Cesariana=Baixo ==> Ano=2023,37,5,1,0.672727,0.090909,0.018182,0.027,0.2973,55
864,{'Classificação_de_Nível_de_Risco': '1'},{'Ano': '2022'},Classificação_de_Nível_de_Risco=1 ==> Ano=2022,37,5,1,0.672727,0.090909,0.018182,0.027,0.2973,55
865,{'Classificação_de_Nível_de_Risco': '1'},{'Ano': '2023'},Classificação_de_Nível_de_Risco=1 ==> Ano=2023,37,5,1,0.672727,0.090909,0.018182,0.027,0.2973,55

In [5]:
ar.present_rules_per_consequent(rules, consequent={'Classificação_de_Nível_de_Risco' : '2'},
                                selection_function=top_5_variant_variables, drop_dups=True,
                                plot=False)

Ano

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3643: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

,rule print,ant_supp,con_supp,rule_supp,confidence,lift
6,Ano=2022 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.072727,0.8,2.4444
7,Ano=2023 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.072727,0.8,2.4444
10,Ano=2013 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.054545,0.6,1.8333
15,Ano=2019 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.036364,0.4,1.2222
16,Ano=2020 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.036364,0.4,1.2222
17,Ano=2021 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.036364,0.4,1.2222
22,Ano=2018 ==> Classificação_de_Nível_de_Risco=2,0.090909,0.327273,0.018182,0.2,0.6111

Região

,rule print,ant_supp,con_supp,rule_supp,confidence,lift
8,Região=Região de Saúde do Alentejo ==> Classif...,0.2,0.327273,0.127273,0.6364,1.9444
12,Região=Região de Saúde Norte ==> Classificação...,0.2,0.327273,0.090909,0.4545,1.3889
18,Região=Região de Saúde do Algarve ==> Classifi...,0.2,0.327273,0.072727,0.3636,1.1111
23,Região=Região de Saúde LVT ==> Classificação_d...,0.2,0.327273,0.036364,0.1818,0.5556

Nº Total de Partos

,rule print,ant_supp,con_supp,rule_supp,confidence,lift
9,Nº Total de Partos=[15188.0 - 17701.0] ==> Cla...,0.2,0.327273,0.127273,0.6364,1.9444
13,Nº Total de Partos=(77748.0 - 150801.0] ==> Cl...,0.2,0.327273,0.090909,0.4545,1.3889
19,Nº Total de Partos=(17701.0 - 24429.0] ==> Cla...,0.2,0.327273,0.072727,0.3636,1.1111
24,Nº Total de Partos=(150801.0 - 193305.0] ==> C...,0.2,0.327273,0.036364,0.1818,0.5556

Nº Cesarianas

,rule print,ant_supp,con_supp,rule_supp,confidence,lift
11,Nº Cesarianas=(5732.0 - 7467.0] ==> Classifica...,0.2,0.327273,0.109091,0.5455,1.6667
14,Nº Cesarianas=[4521.0 - 5732.0] ==> Classifica...,0.2,0.327273,0.090909,0.4545,1.3889
20,Nº Cesarianas=(22744.0 - 47747.0] ==> Classifi...,0.2,0.327273,0.072727,0.3636,1.1111
21,Nº Cesarianas=(47747.0 - 54539.0] ==> Classifi...,0.2,0.327273,0.054545,0.2727,0.8333

Proporção_de_Cesarianas

,rule print,ant_supp,con_supp,rule_supp,confidence,lift
0,Proporção_de_Cesarianas=0.31 ==> Classificação...,0.109091,0.327273,0.109091,1.0,3.0556
1,Proporção_de_Cesarianas=0.32 ==> Classificação...,0.127273,0.327273,0.127273,1.0,3.0556
2,Proporção_de_Cesarianas=0.33 ==> Classificação...,0.036364,0.327273,0.036364,1.0,3.0556
3,Proporção_de_Cesarianas=0.34 ==> Classificação...,0.018182,0.327273,0.018182,1.0,3.0556
4,Proporção_de_Cesarianas=0.38 ==> Classificação...,0.036364,0.327273,0.036364,1.0,3.0556

In [15]:
moderado = rules[rules['consequent'] == {'Classificação_de_Nível_de_Risco' : '2'}]
moderado = moderado[moderado['confidence']> 0.5]
moderado

,antecedent,consequent,rule print,ant_count,con_count,rule_count,ant_supp,con_supp,rule_supp,confidence,lift,# of all records
79,{'Proporção_de_Cesarianas': '0.31'},{'Classificação_de_Nível_de_Risco': '2'},Proporção_de_Cesarianas=0.31 ==> Classificação...,6,18,6,0.109091,0.327273,0.109091,1.0000,3.0556,55
80,{'Proporção_de_Cesarianas': '0.32'},{'Classificação_de_Nível_de_Risco': '2'},Proporção_de_Cesarianas=0.32 ==> Classificação...,7,18,7,0.127273,0.327273,0.127273,1.0000,3.0556,55
81,{'Proporção_de_Cesarianas': '0.33'},{'Classificação_de_Nível_de_Risco': '2'},Proporção_de_Cesarianas=0.33 ==> Classificação...,2,18,2,0.036364,0.327273,0.036364,1.0000,3.0556,55
82,{'Proporção_de_Cesarianas': '0.34'},{'Classificação_de_Nível_de_Risco': '2'},Proporção_de_Cesarianas=0.34 ==> Classificação...,1,18,1,0.018182,0.327273,0.018182,1.0000,3.0556,55
83,{'Proporção_de_Cesarianas': '0.38'},{'Classificação_de_Nível_de_Risco': '2'},Proporção_de_Cesarianas=0.38 ==> Classificação...,2,18,2,0.036364,0.327273,0.036364,1.0000,3.0556,55
84,{'Nível_de_Risco_Cesariana': 'Moderado'},{'Classificação_de_Nível_de_Risco': '2'},Nível_de_Risco_Cesariana=Moderado ==> Classifi...,18,18,18,0.327273,0.327273,0.327273,1.0000,3.0556,55
132,{'Ano': '2022'},{'Classificação_de_Nível_de_Risco': '2'},Ano=2022 ==> Classificação_de_Nível_de_Risco=2,5,18,4,0.090909,0.327273,0.072727,0.8000,2.4444,55
133,{'Ano': '2023'},{'Classificação_de_Nível_de_Risco': '2'},Ano=2023 ==> Classificação_de_Nível_de_Risco=2,5,18,4,0.090909,0.327273,0.072727,0.8000,2.4444,55
159,{'Região': 'Região de Saúde do Alentejo'},{'Classificação_de_Nível_de_Risco': '2'},Região=Região de Saúde do Alentejo ==> Classif...,11,18,7,0.200000,0.327273,0.127273,0.6364,1.9444,55
161,{'Nº Total de Partos': '[15188.0 - 17701.0]'},{'Classificação_de_Nível_de_Risco': '2'},Nº Total de Partos=[15188.0 - 17701.0] ==> Cla...,11,18,7,0.200000,0.327273,0.127273,0.6364,1.9444,55
173,{'Ano': '2013'},{'Classificação_de_Nível_de_Risco': '2'},Ano=2013 ==> Classificação_de_Nível_de_Risco=2,5,18,3,0.090909,0.327273,0.054545,0.6000,1.8333,55
201,{'Nº Cesarianas': '(5732.0 - 7467.0]'},{'Classificação_de_Nível_de_Risco': '2'},Nº Cesarianas=(5732.0 - 7467.0] ==> Classifica...,11,18,6,0.200000,0.327273,0.109091,0.5455,1.6667,55

In [14]:
rules, supp_dict = ar.create_association_rules(df, max_cols=2,
                                               list_of_ants=['Proporção_de_Cesarianas', 'Nível_de_Risco_Cesariana'],
                                               list_of_cols=['Classificação_de_Nível_de_Risco'],
                                               binning_method=five_quantile_based_bins)

ValueError: The columns: Proporção_de_Cesarianas, Nível_de_Risco_Cesariana, from the list of ants, do not appear in the overall list of columns

In [8]:
print(df.columns)

Index(['Região', 'Ano', 'Nº Total de Partos', 'Nº Cesarianas',
       'Proporção_de_Cesarianas', 'Nível_de_Risco_Cesariana',
       'Classificação_de_Nível_de_Risco'],
      dtype='object')